# Generated by Django 5.0.6 on 2025-04-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('classic', 'Classic'), ('rapid', 'Rapid'), ('blitz', 'Blitz')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
